### ISSUE TITLE
QGIS 3.16 keeps crashing

### ISSUE THREAD

**Issue by jafreedman12** [GIS4DEV/GIS4DEV.github.io#11]
Hi There!

I just installed QGIS 3.16 and I have been struggling to keep the program open without it crashing. I am on a MacBook Pro using MacOS Catalina 10.15.7. I currently have QGIS 3.10 and 3.16 installed. When I open 3.16, before the GUI interface appears, I get two error messages: 1) Couldn't load plugin 'qgis_gee_data_catalog' due to an error when calling its classFactory() method , 2) Couldn't load plugin 'OSMDownloader' due to an error when calling its classFactory() method. I believe that these plugins were installed within QGIS3.10. If and when the QGIS homepage opens (which happens about half the time), the processing toolbar does not appear. So, I go into "Manage Plugins" and try to click on/activate Processing, and then QGIS crashes again. QGIS 3.10 still runs effectively on my. laptop at this time.

**Comment by josephholler** [comment]
If old plugins are causing problems with new installations, one thing to try is to create a new QGIS profile. Plugins and other custom settings you may have from older QGIS versions will be ignored in the new profile. If you can, try going to:
*Settings* -> *User Profiles* -> *New Profile...*

I was unable to install that Google Earth Engine Data Catalog plugin on 3.16. There was a bug that has apparently been fixed in the source code, but not yet pushed to the QGIS plugin repository. https://github.com/gee-community/qgis-earthengine-plugin/issues/76 

I was able to install OSMDownloader plugin version 1.0.3 

Hopefully the issue was just these plugins, or out-of-date settings in the user profile.

**Comment by jafreedman12** [comment]
It turns out I had downloaded the KyngChaos version of QGIS 3.16 and that was what was causing the crashes. I was unable to download the "official" 3.16 downloader in Chrome, but was successful in Safari. So we are all good now!  Thanks
