### ISSUE TITLE
Spacing issues?

### ISSUE THREAD

**Issue by mtango99** [GIS4DEV/GIS4DEV.github.io#12]
Hey all, 

Anyone having spacing issues when publishing from your text editor (I'm using Notepad++) to the GitHub website? 

Example 1: 
```
Open Source GIS
2/28/21
```
becomes "Open Source GIS 2/28/21"

Example 2:
```
A


B
```
becomes
```
A

B
```
(or maybe that space is just a "space after paragraph" sort of thing?)

Also... if anyone has any better ways to indent than "`&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`"
(...and as I'm typing here there are two lines between "thing?)" and "Also"-- but when I publish there's only one line space.

**Comment by josephholler** [comment]
You've correctly noticed that by default, Markdown is trying to be simple. It's left-justified and doesn't have special paragraph formatting options. If there is a blank line in between text, it assumes that it is a new paragraph. If not, it assumes the text just keeps going in the same paragraph.

`> here's a quote, which might satisfy your indentation question. Start the line with a greater-than symbol.`

> here's a quote, which might satisfy your indentation question. Start the line with a greater-than symbol.

Otherwise, you can insert HTML tags as much as you like in your Markdown documents. Jeckyll will use the HTML tags just as they are. Here's a good [guide to html](https://www.w3schools.com/html/). A handy tag for your situation is '<br>' to end one line without creating a new paragraph.

**Comment by mtango99** [comment]
Thanks, Joe-- that helps!
&nbsp;  
&nbsp;  
Also for anyone with the same question, just found more info [here](https://dotcms.com/docs/latest/markdown-syntax#:~:text=To%20add%20a%20single%20extra,replacing%20the%20periods%20with%20spaces).): 
>"To add a single extra line after a paragraph, add two extra spaces at the end of the text. To add an extra line of space between paragraphs, add the HTML `&nbsp;` code, followed by two extra spaces (e.g. `&nbsp..` , replacing the periods with spaces)."

`&nbsp  `
`&nbsp  `
Like that^ -- creates blank lines like above. (the two spaces without the `&nbsp` didn't do anything for me though)

**Comment by josephholler** [comment]
to follow up, `&nbsp;` is HTML code for a single space. So those instructions are essentially telling to to add paragraphs that consist of a single blank space, so you don't see anything except blank lines.

&emsp;This is indented with one symbol, the em space `&emsp;` A good reference for HTML symbols is [here](https://www.w3schools.com/charsets/ref_utf_punctuation.asp)

**Comment by mtango99** [comment]
Thank you!!
