### ISSUE TITLE
Gravity model: expectations vs. challenges/optional

### ISSUE THREAD

**Issue by majacannavo** [GIS4DEV/GIS4DEV.github.io#14]
I'm a bit confused on exactly what the deliverables are for this assignment. Are we creating three separate models: one for the gravity model of spatial interaction, one for preprocessing Homeland Security hospital data, and one for preprocessing target features? Or are the second two optional? Also, are the "gravity model challenges" reminders of things to remember or are they optional things to try?

**Comment by josephholler** [comment]
Good question. If we had been in person, I would have been watching how the evening progressed and gauging on the fly how far into the "challenges" to ask you all to go. 

At a minimum, everyone should go for a working gravity model that allows you to modify the parameters for friction of distance and input/target weights. 

In order to make a sensible map of this, we do need filter the hospitals and aggregate them by town. The most reproducible way to do that is with one or two models. In the write-up, I split this into two with one that would be generally applicable to many cases, and one preprocessing the specific challenges of the hospitals.

*But*, if folks are just wrapping up their main gravity models, then the other hospital preprocessing steps could just be done in QGIS without a model. Just document your processing steps, e.g. in a workflow diagram.

**Comment by mtango99** [comment]
In terms of preprocessing the hospital data, I'm a bit confused as to what that entails given the attribute table doesn't delineate between open/closed hospitals and public ICU/not. Is there any information available on this that doesn't require going through each row? 

Also, what is the purpose of the HSAs in our model?

**Comment by josephholler** [comment]
Row by row? No coxswain here! The attribute table includes useful enough information: type of hospital, status, and the number of beds.

Just keep the HSAs for visualization / comparison with your own hospital catchments.

**Comment by mtango99** [comment]
OHH I thought we had to download that data you listed at the bottom, assuming we'd have to apply the model to a new dataset-- now I see the attributes in the original data.
