### ISSUE TITLE
Save Ben and Robbie

### ISSUE THREAD

**Issue by rmkelley** [GIS4DEV/GIS4DEV.github.io#2]
When you use astext(st_x()) or y it returns nothing even though just st_x was previously returning a float. Any ideas for why?

**Comment by josephholler** [comment]
The `ST_x()` and `ST_y()` functions take the input of a point geometry and give you a decimal number for the x-coordinate or the y-coordinate. Check out the [functions guide](http://www.gaia-gis.it/gaia-sins/spatialite-sql-4.2.0.html#p5) for SpatiaLite.

`astext()` takes a geometry input, so that it can translate the geometry data into readable text for you. It doesn't know what to do with a decimal number.
