### ISSUE TITLE
Developing this Model for Other Regions

### ISSUE THREAD

**Issue by evankilli** [GIS4DEV/GIS4DEV.github.io#21]
For a bit, while starting to figure out the second part of the project, looking at areas beyond Vermont, I briefly considered investigating areas in the South, given my roots in Florida and connection to other Southern States through friends and family. Looking at the what I would need to do, though, I remembered that New England is fairly unique in the US in having next to no unincorporated land - almost all land in this corner of the country is part of a town or city. Back home, however, much - if not most - land is unincorporated county land, not a part of any formalized county subdivision. 

How would the model we've been creating work in these cases where town and city boundaries are much more irregular and much less relevant than in the New England case? Would using divisions like Census Tracts or ZipCodes be effective in this case? If it weren't for the fact that unincorporated land is often fairly populated, unlike the small areas of Northern New England that are unincorporated like northern areas of Maine, county subdivisions would certainly work, but given the situation that exists currently, it seems like continuing to use county subdivisions outside the Northeast might lead us to lose out on precision.

**Comment by josephholler** [comment]
Zip codes would be great. The Dartmouth atlas is based on zip codes. It's really easy to match billing records to zip code tabulation areas because you can just strip out the zip code!  It's true that there are some very strange county subdivision boundaries in the south and west, including municipalities that cross county lines (Kansas City MO is one of those-- it causes a royal headache when trying to map county-level COVID data).

Unfortunately I've been unable to download zip code geographies from the Census for the past week, as if the web server hosting that file is having trouble. If you can do it, feel free to use them!

**Comment by evankilli** [comment]
Awesome! I've started working on Northeast hospitals already, so this was more of a general question, but I might check this out later too!
