### ISSUE TITLE
Distance matrix not working with actual data

### ISSUE THREAD

**Issue by jackson-mumper** [GIS4DEV/GIS4DEV.github.io#24]
Hi all! 

I'm currently trying to run the gravity model on New England towns with my prepared hospitals layer, and I'm running into an error with the distance matrix. It keeps telling me:

featList = index.nearestNeighbor(inGeom.asPoint(), nPoints)
ValueError: Null geometry cannot be converted to a point.
Error encountered while running Distance matrix

Has anyone encountered this issue? The models works fine with the VT data and the centroids on their own seem to be working properly so I'm not sure where it's going wrong.

Thanks!

**Comment by mtango99** [comment]
Is there any way you can filter out the rows with null geometries? Maybe null geometries correspond to some null values in the attribute table?

________________________________

**Comment by sanjana-roy** [comment]
I had the same issue. The null geometries match some places in the middle of the ocean that don't seem to exist i.e. there actually aren't any geometries there. You would have to allow for only weights greater than 0 to be selected from the very beginning.

**Comment by josephholler** [comment]
Yes, Sanjana is correct.  I didn't notice this problem because I had filtered for weights greater than `0` at the beginning of my model. The `null` geometries also all have `0` population. The field calculator function `num_geometries($geometry)` can tell you how many geometry parts each town has, and there is a small batch with `0` parts and `0` people.
Also, there is a `remove null geometries` tool which could be handy in a situation such as this.
