### ISSUE TITLE
Population Density

### ISSUE THREAD

**Issue by mtango99** [GIS4DEV/GIS4DEV.github.io#26]
Is anyone else's population densities in the millions...?

**Comment by majacannavo** [comment]
I don't think we actually need to include pop density on the map if that helps--I didn't end up calculating it.

**Comment by vinfalardeau** [comment]
I have a few catchment areas around NYC with populations in the millions, but otherwise it's mostly in the tens or hundreds of thousands, and I just tried doing density (population per sq. km) and actually got lower values...  Did you extract just the rows of the attribute table with the maximum potential for each town?  Because I was having a hard time with that earlier and that seems like something that could lead to much higher values (e.g. taking the sum of input weights for _k_ times more rows).

I think Maja is right that we don't need density, but I imagine if you've got densities in the millions then the raw populations must be even higher? Unless the areal units are a lot larger than square kilometers

**Comment by majacannavo** [comment]
I think it might have gotten removed from the page--it says we needed four layers on our web map but now there are only three listed (and I think the fourth was pop density)

**Comment by josephholler** [comment]
Yes: I needed to simplify this a bit-- removed any static map design or population density. 

Could `area($geometry)` be calculating in degrees<sup>2</sup> ?  If so, try reprojecting or using `$area` which can manage geodesic calculation in the units specified by the project's length/area calculation settings.

**Comment by mtango99** [comment]
That was it! $area worked. Thanks

________________________________
