### ISSUE TITLE
Excel file location for Rosgen work?

### ISSUE THREAD

**Issue by emmaclinton** [GIS4DEV/GIS4DEV.github.io#29]
Hi! I'm having some trouble locating the excel notebook. Could someone point me in the right direction?

**Comment by josephholler** [comment]
Sorry! I thought I saw that this was closed right after it opened.  
I want to ask the same question: I created a notebook with space to take notes on all of the formulas and I accidentally deleted it. I know, you're going to tell me "that's why we're using GitHub!" and here's the rub: I did a bunch of work on the repository and then committed a large batch of changes all at once. In order to recover the notebook I'd have to revert the whole commit and lose more than I'd gain. Lesson learned: commit frequently, in small batches of discrete work.  I can see exactly when I deleted it in my GitHub history but it isn't worth recovering.
