### ISSUE TITLE
Add to Canvas 

### ISSUE THREAD

**Issue by sarahhaedrich** [GIS4DEV/GIS4DEV.github.io#8]
Hi Joe,

I'm trying to make centroids of the county data from Lab09. Here is my query:
CREATE TABLE centroids As
SELECT *, st_centroid(geometry)
FROM counties

I look at the table in the Database Manager and all the table information is there, including a column name labeled "st_centroid" with "POINT" data. When I add the data to the canvas however, all the column names go blank and no data is carried over. Do you know why this is happening?

Best,
Sarah

**Comment by josephholler** [comment]
There's a few things you might try:

1) alias the st_centroid() column to a good column name (AS .... )
2) choose a different table name. 'centroids' might conflict with function names...  this is probably not the cause of the problem, but anyway choose a table name more specific to the content, e.g. county_centroids
3) there might be confusion from having two geometry columns (one polygon, one point), so try to be sure to get the new columns registered in geometry_columns table using the select populate_geometry_columns() function so that you can be certain which geometry type you're trying to visualize in QGIS.
4) one last thought: QGIS tends to remember the schema of a table from the first time it was added, so if you had previously made incorrect versions of 'centroids' and added them to the canvas, you might need to close out QGIS and re-open.

**Comment by sarahhaedrich** [comment]
Thank you, I got it to work.
________________________________
